In [2]:
import gym
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from collections import deque
import numpy as np
import random

Using TensorFlow backend.


In [3]:
# with help from https://keon.io/deep-q-learning/
# Adopted from my attempts at DQN with pacman
memory = deque(maxlen=2000)
gamma = 0.95  
epsilon = 0.08  # exploration rate
epsilon_min = 0.01
epsilon_decay = 0.99
learning_rate = 0.001
batch_size = 32
memory = []

def build_network():
    model = Sequential()
    model.add(Dense(125,input_dim=4, activation='relu'))
    model.add(Dense(50,activation='relu'))
    model.add(Dense(2, activation='linear'))
    try:
        model.load_weights("model.h5")
        print "LOADEd weights"
    except:
        pass
    model.compile(loss='mse',optimizer=Adam(lr=learning_rate)) 
    return model
model = build_network()
def remember(s,a,r,sp,d):
    memory.append((s,a,r,sp,d))
def update(memory):
#     Take random sample from memory
    batch = random.sample(memory, batch_size) 
#     Train network on batch
    for s, a, r, sp, d in batch:
#       if state is final there is no future rewards
        target = r
#       discounted future rewards
        if not d:
            target = r + gamma * \
               np.amax(model.predict(sp)[0])
                
#       Get pred then replace action with our target
        target_f = model.predict(s)
        print(target_f)
        target_f[0][a] = target
        model.fit(s, target_f, epochs=1, verbose=0)
def act(obs):
    if np.random.rand() <= epsilon:
        # The agent acts randomly
        return env.action_space.sample()
  
    # Predict the reward value based on the given state
    act_values = model.predict(obs)

    # Pick the action based on the predicted reward
    return np.argmax(act_values[0])


LOADEd weights


In [4]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(5000):
    obs = env.reset() # reset for each new trial
    obs = np.reshape(obs,[1,4])
#     print(observation)
    for t in range(500): # run for 100 timesteps or until done, whichever is first
        if i_episode > 4900:
            env.render()
        
        action = act(obs)
#         print(action)
        prv_obs = obs
        obs, reward, done, info = env.step(action)
        obs = np.reshape(obs,[1,4])
        remember(prv_obs,action,reward,obs,done)
        
        if done:
            model.save_weights("model.h5")
            print("Episode finished after {} timesteps".format(t+1))
            break
    if len(memory) >= batch_size:
        update(memory)

[2017-08-23 17:13:05,379] Making new env: CartPole-v0


Episode finished after 132 timesteps
[[ 21.7650795   21.88814163]]
[[ 21.74040985  21.54913139]]
[[ 21.29796982  21.15623665]]
[[ 16.82031631  16.85103607]]
[[ 19.05059814  18.90251541]]
[[ 15.81829262  15.76116848]]
[[ 20.91431046  21.04133797]]
[[ 8.17928123  8.12115955]]
[[ 20.73432732  20.65188217]]
[[ 17.25042534  17.25590515]]
[[ 8.29968262  8.25642204]]
[[ 16.52077866  16.38802338]]
[[ 19.99848938  19.76761055]]
[[ 18.15895081  18.01927567]]
[[ 20.34822083  20.35060883]]
[[ 20.1396656  20.1120472]]
[[ 20.17744637  19.91892242]]
[[ 17.6196003   17.45324326]]
[[ 19.83519936  19.78566742]]
[[ 9.0556879   9.07238579]]
[[ 19.07175255  19.24975395]]
[[ 19.9462738   19.74985123]]
[[ 13.42955685  13.40143204]]
[[ 18.41012001  18.15430832]]
[[ 18.9301281   18.79329872]]
[[ 19.8681221   19.78030586]]
[[ 19.44160461  19.36750984]]
[[ 19.96144485  19.81957054]]
[[ 18.97218132  19.31697655]]
[[ 17.80209923  17.63275146]]
[[ 20.22430801  19.85562325]]
[[ 14.65811539  14.4525032 ]]
Episode fin

KeyboardInterrupt: 